server:
  port: 8081

spring:
  application:
    name: central-monitoring-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

monitoring:
  temperature:
    threshold: 35
  humidity:
    threshold: 50